#pragma once

#include "RE/H/hkArray.h"
#include "RE/H/hkRefPtr.h"
#include "RE/H/hkQsTransform.h"
#include "RE/H/hkaSkeleton.h"

namespace RE
{
	/// hkaSkeletonMapperData is the data used at run-time by an hkaSkeletonMapper. It consists of a set of
	/// both simple (one-to-one) and chain (m-to-n) mappings.
	/// The information in this class can easily be generated by the utility class hkaSkeletonMapperUtils
	class hkaSkeletonMapperData
	{
	public:
		enum MappingType : int32_t
		{
			/// Ragdoll mapping
			HK_RAGDOLL_MAPPING = 0,

			/// Animation retargeting mapping
			HK_RETARGETING_MAPPING = 1
		};

		/// Defines a 1-1 mapping between a single bone of A and a single bone of B.
		struct SimpleMapping
		{
			// members
			int16_t       m_boneA{ 0 };         // 00
			int16_t       m_boneB{ 0 };         // 02
			char          pad04[12];            // 04
			hkQsTransform m_aFromBTransform{};  // 04
		};
		static_assert(sizeof(SimpleMapping) == 0x40);

		/// Defines a n-to-m mapping between a chain of bones of A and a chain of bones of B.
		struct ChainMapping
		{
			// members
			int16_t       m_startBoneA;            // 00
			int16_t       m_endBoneA;              // 02
			int16_t       m_startBoneB;            // 04
			int16_t       m_endBoneB;              // 06
			char          pad08[8];                // 08
			hkQsTransform m_startAFromBTransform;  // 10
			hkQsTransform m_endAFromBTransform;    // 40
		};
		static_assert(sizeof(ChainMapping) == 0x70);

		hkaSkeletonMapperData() = default;
		hkaSkeletonMapperData(const hkaSkeletonMapperData& other) = default;
		hkaSkeletonMapperData& operator=(const hkaSkeletonMapperData& other) = default;
		~hkaSkeletonMapperData() = default;

		// members
		hkRefPtr<hkaSkeleton>  m_skeletonA;                  // 00
		hkRefPtr<hkaSkeleton>  m_skeletonB;                  // 08
		hkArray<SimpleMapping> m_simpleMappings;             // 10
		hkArray<ChainMapping>  m_chainMappings;              // 20
		hkArray<int16_t>       m_unmappedBones;              // 30
		hkQsTransform          m_extractedMotionMapping;     // 40
		bool                   m_keepUnmappedLocal{ true };  // 70
		char                   pad71[3];                     // 71
		MappingType            m_mappingType{ MappingType ::HK_RETARGETING_MAPPING};  // 74
		char                   pad78[8];                     // 78
	};
	static_assert(sizeof(hkaSkeletonMapperData) == 0x80);
	static_assert(alignof(hkaSkeletonMapperData) == 0x10);
}
