#pragma once

#include "RE/H/hkStringPtr.h"
#include "RE/H/hkbBindable.h"
#include "RE/H/hkbContext.h"

namespace RE
{
	class hkbEvent;
	class hkbNode;

	/// Stores returned info about a child of a node.
	struct hkbNodeChildInfo
	{
		hkbNodeChildInfo() = default;

		// members
		hkbNode* node{};                 // 00 - The child node template
		bool     ignoreEvents{ false };  // 08 - If true, events will not be sent to the nodes and events generated by the node will not be forwarded
		bool     reset{ false };         // 09 - Whether to reset the node asap (deactivate and then activate)
		bool     syncToParent{ false };  // 0A - Whether or not to synchronize this node with the parent
		bool     stopped{ false };       // 0B - Whether or not the parent wants this child to be moved forward in time
		char     pad0C[4];               // 0C
	};
	static_assert(sizeof(hkbNodeChildInfo) == 0x10);

	class hkbNode : public hkbBindable
	{
	public:
		inline static constexpr auto RTTI = RTTI_hkbNode;
		inline static constexpr auto VTABLE = VTABLE_hkbNode;

		/// Stores returned info about the children of a node.
		struct ChildrenInfo
		{
			ChildrenInfo(hkArray<hkbNodeChildInfo>& childInfos) :
				childInfos(childInfos) {}

			// members
			hkArray<hkbNodeChildInfo>& childInfos;    // 00 - An array of child info (must be allocated by the caller)
			bool                       ignoreEvents;  // 08
			bool                       reset;         // 09
			bool                       syncToParent;  // 0A
			uint8_t                    unk0B;         // 0B
			char                       pad0C[4];      // 0C
		};
		static_assert(sizeof(ChildrenInfo) == 0x10);

		/// Flags used when calling GenNumChildren() or GetChildren().
		enum class GetChildrenFlagBits : int32_t
		{
			kActiveOnly = 1 << 0,      // If true, only return the active children (otherwise, all children).
			kGeneratorsOnly = 1 << 1,  // If true, only return generators (else also return modifiers).
			// If true, the behavior graphs pointed to by hkbBehaviorReferenceGenerators
			// will be ignored (along with all of their descendants).
			kIgnoreReferencedBehaviour = 1 << 2
		};
		using GET_CHILDREN_FLAGS = stl::enumeration<GetChildrenFlagBits, int32_t>;

		enum class CloneState : uint8_t
		{
			kDefault = 0,
			kTemplate = 1,
			kClone = 2,
			kShareable = 3
		};

		hkbNode() { stl::emplace_vtable(this); }
		~hkbNode() override = default;  // 00

		// add
		virtual void                Activate([[maybe_unused]] const hkbContext& a_context) {}                                                                                                                       // 04
		virtual void                Update([[maybe_unused]] const hkbContext& a_context, [[maybe_unused]] float a_timestep) { userData |= 1; }                                                                      // 05
		virtual void                handleEvent([[maybe_unused]] const hkbContext& ctx, [[maybe_unused]] hkbEvent& event) {}                                                                                        // 06
		virtual void                Deactivate([[maybe_unused]] const hkbContext& a_context) {}                                                                                                                     // 07
		virtual int32_t             getMaxNumChildren([[maybe_unused]] GET_CHILDREN_FLAGS flags) { return 2; }                                                                                                      // 08
		virtual void                getChildren([[maybe_unused]] GET_CHILDREN_FLAGS flags, [[maybe_unused]] ChildrenInfo& ans) {}                                                                                   // 09
		virtual bool                isValid([[maybe_unused]] hkStringPtr& err) const { return true; }                                                                                                               // 0A
		virtual void                precompute([[maybe_unused]] const hkbContext& ctx) {}                                                                                                                           // 0B
		virtual hkbNode*            cloneNode([[maybe_unused]] hkbBehaviorGraph& rootBehavior) const { return nullptr; }                                                                                            // 0C
		virtual hkReferencedObject* createInternalState() { return nullptr; }                                                                                                                                       // 0D
		virtual void                getInternalState([[maybe_unused]] hkReferencedObject& internalState) const {}                                                                                                   // 0E
		virtual void                getInternalStateUser([[maybe_unused]] const hkbBehaviorGraph& rootBehavior, [[maybe_unused]] hkReferencedObject& internalState) const {}                                        // 0F
		virtual void                setInternalState([[maybe_unused]] const hkReferencedObject& internalState) {}                                                                                                   // 10
		virtual void                setInternalStateUser([[maybe_unused]] const hkbContext& context, [[maybe_unused]] const hkReferencedObject& internalState, [[maybe_unused]] void* nodeIdToInternalStateMap) {}  // 11
		virtual void                getActiveEvents([[maybe_unused]] void* activeEvents) const {}                                                                                                                   // 12
		virtual bool                isTransitionEffect() const { return false; }                                                                                                                                    // 13
		virtual void                getActiveVariablesSpecial([[maybe_unused]] void* activeVariables) const {}                                                                                                      // 14
		virtual bool                isGenerator() const { return false; }                                                                                                                                           // 15
		virtual bool                isGraph() const { return false; }                                                                                                                                               // 16

		HK_HEAP_REDEFINE_NEW();

		// members
		uint64_t    userData{ 0 };                        // 30
		hkStringPtr name;                                 // 38
		int16_t     id{ -1 };                             // 40
		CloneState  cloneState{ CloneState ::kDefault };  // 42
		char        pad43[5];                             // 43
	};
	static_assert(sizeof(hkbNode) == 0x48);

	using GET_CHILDREN_FLAG = hkbNode::GetChildrenFlagBits;
	using GET_CHILDREN_FLAGS = hkbNode::GET_CHILDREN_FLAGS;
}
